import json
from pathlib import Path

sessions = json.loads(Path(r"d:\projects\interspeech2026\data\sessions.json").read_text(encoding="utf-8"))

# primary topic per session id
TOPIC = {
    # perception, phonetics, production
    "mon-002": "phonetics",
    "mon-011": "phonetics",
    "mon-020": "phonetics",
    "mon-029": "phonetics",
    "mon-032": "representation",
    "mon-034": "phonetics",
    "tue-037": "phonetics",
    "tue-046": "phonetics",
    "tue-048": "signal",
    "tue-052": "phonetics",
    "tue-056": "phonetics",
    "tue-065": "phonetics",
    "tue-075": "phonetics",
    "tue-085": "phonetics",
    "tue-086": "phonetics",
    "wed-104": "phonetics",
    "wed-115": "phonetics",
    "wed-125": "phonetics",
    "wed-126": "phonetics",
    "wed-133": "phonetics",
    "thu-152": "phonetics",
    "thu-154": "signal",
    "thu-161": "emotion",
    "thu-172": "phonetics",
    "thu-182": "phonetics",
    # speaker
    "mon-003": "speaker",
    "tue-038": "speaker",
    "wed-095": "speaker",
    "wed-127": "speaker",
    "thu-153": "speaker",
    "thu-160": "diarization",
    "thu-162": "speaker",
    "thu-189": "speaker",
    "wed-105": "diarization",
    "wed-116": "diarization",
    # asr
    "mon-006": "asr-multitalker",
    "mon-007": "asr-decoding",
    "mon-010": "asr",
    "mon-017": "retrieval",
    "tue-042": "asr",
    "tue-045": "multilingual",
    "tue-051": "asr",
    "tue-058": "asr",
    "tue-070": "asr",
    "tue-078": "asr",
    "tue-079": "multilingual",
    "tue-089": "asr",
    "wed-109": "asr",
    "wed-119": "asr",
    "wed-120": "asr",
    "wed-121": "asr",
    "wed-139": "translation",
    "wed-146": "asr",
    "wed-147": "asr",
    "thu-156": "asr",
    "thu-157": "asr",
    "thu-158": "retrieval",
    "thu-166": "asr",
    "thu-170": "asr",
    "thu-177": "asr",
    "thu-188": "asr",
    # tts
    "mon-005": "tts",
    "mon-016": "tts",
    "mon-028": "tts",
    "mon-036": "tts",
    "tue-041": "tts",
    "tue-050": "singing",
    "tue-060": "tts",
    "tue-061": "tts",
    "tue-069": "tts",
    "tue-088": "tts",
    "wed-098": "tts",
    "wed-102": "singing",
    "wed-108": "tts",
    "wed-117": "generation",
    "wed-118": "tts",
    "wed-129": "tts",
    "wed-138": "tts",
    "thu-155": "tts",
    "thu-165": "tts",
    "thu-176": "tts",
    "thu-187": "voice-conversion",
    # enhancement
    "mon-015": "enhancement",
    "mon-024": "enhancement",
    "tue-040": "enhancement",
    "tue-049": "separation",
    "tue-076": "separation",
    "tue-077": "enhancement",
    "wed-107": "enhancement",
    "wed-124": "enhancement",
    "wed-128": "enhancement",
    "wed-137": "separation",
    "thu-175": "enhancement",
    "thu-185": "separation",
    "thu-186": "enhancement",
    # codec
    "mon-031": "codec",
    "tue-064": "codec",
    "wed-097": "codec",
    "tue-068": "evaluation",
    # deepfake
    "mon-013": "deepfake",
    "mon-022": "deepfake",
    "tue-066": "deepfake",
    "tue-072": "deepfake",
    "tue-083": "deepfake",
    "wed-135": "deepfake",
    "thu-171": "deepfake",
    "thu-173": "deepfake",
    "thu-184": "deepfake",
    # llm / audio lm
    "mon-009": "representation",
    "mon-019": "audio-llm",
    "mon-033": "audio-llm",
    "tue-062": "audio-llm",
    "tue-081": "audio-llm",
    "wed-099": "representation",
    "wed-110": "audio-llm",
    "wed-142": "dialogue",
    "wed-143": "representation",
    "wed-148": "slu",
    "thu-167": "audio-llm",
    "thu-169": "representation",
    "thu-181": "representation",
    # dialogue / full duplex
    "mon-008": "dialogue",
    "tue-080": "dialogue",
    "tue-091": "dialogue",
    "wed-100": "dialogue",
    "thu-179": "dialogue",
    # emotion
    "mon-012": "emotion",
    "mon-021": "emotion",
    "tue-047": "emotion",
    "tue-057": "emotion",
    "wed-094": "emotion",
    "wed-134": "emotion",
    "thu-183": "emotion",
    # multimodal
    "mon-025": "multimodal",
    "tue-084": "multimodal",
    "thu-178": "multimodal",
    # health
    "mon-018": "health",
    "mon-027": "health",
    "tue-044": "health",
    "tue-053": "health",
    "tue-063": "health",
    "tue-071": "health",
    "tue-092": "health",
    "wed-101": "health",
    "wed-103": "health",
    "wed-112": "health",
    "wed-122": "health",
    "wed-123": "health",
    "wed-131": "health",
    "wed-140": "health",
    "wed-141": "health",
    "wed-149": "health",
    "thu-159": "health",
    "thu-180": "health",
    # spatial / events
    "mon-004": "spatial",
    "mon-014": "evaluation",
    "mon-023": "events",
    "mon-026": "evaluation",
    "mon-030": "events",
    "tue-039": "events",
    "tue-059": "spatial",
    "tue-067": "events",
    "tue-087": "spatial",
    "wed-096": "evaluation",
    "wed-106": "events",
    "wed-136": "evaluation",
    "thu-163": "spatial",
    "thu-164": "spatial",
    "thu-168": "evaluation",
    "thu-174": "events",
    # community / data / learning
    "tue-043": "data",
    "tue-054": "community",
    "tue-073": "community",
    "tue-074": "learning",
    "tue-082": "data",
    "tue-090": "learning",
    "tue-093": "community",
    "wed-111": "data",
    "wed-130": "multilingual",
    "wed-132": "children",
    "wed-144": "signal",
    "wed-145": "multimodal",
    "wed-150": "trust",
    "wed-151": "data",
    # front matter
    "sun-001": "overview",
    "mon-keynote": "overview",
    "tue-055": "overview",
    "wed-113": "overview",
    "wed-114": "overview",
    "mon-035": "challenges",
    "fri-190": "overview",
    "sat-191": "overview",
}

missing = [s["id"] for s in sessions if s["id"] not in TOPIC]
print("missing", missing)
from collections import Counter
c = Counter(TOPIC[s["id"]] for s in sessions)
papers = Counter()
for s in sessions:
    papers[TOPIC[s["id"]]] += len(s["items"])
print("sessions", dict(c))
print("papers", dict(papers))

out = []
for s in sessions:
    topic = TOPIC[s["id"]]
    out.append({
        "topic": topic,
        "id": s["id"],
        "day": s["day"],
        "time": s["time"],
        "format": s["format"],
        "title": s["title"],
        "output_path": s["output_path"],
        "items": [
            {
                "paper_id": it["paper_id"],
                "title": it["title"],
                "presenter": it["presenter"],
                "abstract": it["abstract"],
            }
            for it in s["items"]
        ],
    })
Path(r"d:\projects\interspeech2026\data\topics_assigned.json").write_text(
    json.dumps(out, ensure_ascii=False), encoding="utf-8"
)
print("wrote", len(out))
